-- MySQL Script generated by MySQL Workbench
-- Thu Nov 16 10:57:00 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema INE_Inventarios
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema INE_Inventarios
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `INE_Inventarios` DEFAULT CHARACTER SET utf8 ;
USE `INE_Inventarios` ;

-- -----------------------------------------------------
-- Table `INE_Inventarios`.`Persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `INE_Inventarios`.`Persona` (
  `idPersona` INT NOT NULL AUTO_INCREMENT,
  `Nombre_Per` VARCHAR(45) NULL,
  `Ape_Pat_Per` VARCHAR(45) NULL,
  `Ape_Mat_Per` VARCHAR(45) NULL,
  `Curp_Per` VARCHAR(20) NULL,
  `Fecha_Nac_Per` DATE NULL,
  `Calle_Per` VARCHAR(45) NULL,
  `Colonia_Per` VARCHAR(45) NULL,
  `CP_Per` INT NULL,
  `Tel_Per` CHAR(12) NULL,
  `NoLic_Per` VARCHAR(20) NULL,
  `NoCred_Per` VARCHAR(20) NULL,
  PRIMARY KEY (`idPersona`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `INE_Inventarios`.`Area`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `INE_Inventarios`.`Area` (
  `idArea` INT ZEROFILL NOT NULL AUTO_INCREMENT,
  `Nombre_Area` VARCHAR(45) NULL,
  PRIMARY KEY (`idArea`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `INE_Inventarios`.`Puestos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `INE_Inventarios`.`Puestos` (
  `idPuesto` INT NOT NULL AUTO_INCREMENT,
  `Nom_Pues` VARCHAR(45) NULL,
  `Salario_Pues` DOUBLE NULL,
  `Area_idArea` INT ZEROFILL NOT NULL,
  PRIMARY KEY (`idPuesto`, `Area_idArea`),
  INDEX `fk_Puestos_Area1_idx` (`Area_idArea` ASC),
  CONSTRAINT `fk_Puestos_Area1`
    FOREIGN KEY (`Area_idArea`)
    REFERENCES `INE_Inventarios`.`Area` (`idArea`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `INE_Inventarios`.`Empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `INE_Inventarios`.`Empleado` (
  `RFC_Emp` VARCHAR(20) NOT NULL,
  `Puestos_idPuesto` INT NOT NULL,
  `Persona_idPersona` INT NOT NULL,
  PRIMARY KEY (`RFC_Emp`, `Puestos_idPuesto`, `Persona_idPersona`),
  INDEX `fk_Empleado_Puestos_idx` (`Puestos_idPuesto` ASC),
  INDEX `fk_Empleado_Persona1_idx` (`Persona_idPersona` ASC),
  CONSTRAINT `fk_Empleado_Puestos`
    FOREIGN KEY (`Puestos_idPuesto`)
    REFERENCES `INE_Inventarios`.`Puestos` (`idPuesto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Empleado_Persona1`
    FOREIGN KEY (`Persona_idPersona`)
    REFERENCES `INE_Inventarios`.`Persona` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `INE_Inventarios`.`Modulos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `INE_Inventarios`.`Modulos` (
  `idModulos` INT NOT NULL AUTO_INCREMENT,
  `Nombre_Mod` VARCHAR(45) NULL,
  `Caract_Mod` VARCHAR(45) NULL,
  `Descrip_Mod` VARCHAR(45) NULL,
  PRIMARY KEY (`idModulos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `INE_Inventarios`.`Permisos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `INE_Inventarios`.`Permisos` (
  `idPermisos` INT NOT NULL AUTO_INCREMENT,
  `Modulos_idModulos` INT NOT NULL,
  `Nom_Per` VARCHAR(45) NULL,
  `Fecha_Per` DATE NULL,
  `Autoridad_Per` VARCHAR(45) NULL,
  PRIMARY KEY (`idPermisos`, `Modulos_idModulos`),
  INDEX `fk_Permisos_Modulos1_idx` (`Modulos_idModulos` ASC),
  CONSTRAINT `fk_Permisos_Modulos1`
    FOREIGN KEY (`Modulos_idModulos`)
    REFERENCES `INE_Inventarios`.`Modulos` (`idModulos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `INE_Inventarios`.`Asignacion_Usr`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `INE_Inventarios`.`Asignacion_Usr` (
  `idAsignacion` INT NOT NULL AUTO_INCREMENT,
  `Fecha_Asig` DATE NULL,
  `Status_Asig` VARCHAR(45) NULL,
  `Obsr_Asig` VARCHAR(180) NULL,
  PRIMARY KEY (`idAsignacion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `INE_Inventarios`.`Solicitudes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `INE_Inventarios`.`Solicitudes` (
  `idSolicitudes` INT NOT NULL AUTO_INCREMENT,
  `Status_Sol` VARCHAR(45) NULL,
  `Fecha_Sol` DATE NULL,
  `Tipo_Sol` VARCHAR(45) NULL,
  `idUsuario_Sol` INT NULL,
  PRIMARY KEY (`idSolicitudes`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `INE_Inventarios`.`Respuesta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `INE_Inventarios`.`Respuesta` (
  `idRespuesta` INT NOT NULL AUTO_INCREMENT,
  `Fecha_Res` DATE NULL,
  `Status_Res` VARCHAR(45) NULL,
  `Tipo_Res` VARCHAR(45) NULL,
  `idUsuario_Res` INT NULL,
  PRIMARY KEY (`idRespuesta`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `INE_Inventarios`.`Tipo_Usr`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `INE_Inventarios`.`Tipo_Usr` (
  `idTipo_Usr` INT NOT NULL,
  `Nombre_TipoUsr` VARCHAR(45) NULL,
  PRIMARY KEY (`idTipo_Usr`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `INE_Inventarios`.`Solicitud_Vehiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `INE_Inventarios`.`Solicitud_Vehiculo` (
  `idSolicitud_Vehiculo` INT NOT NULL AUTO_INCREMENT,
  `Fecha_SolVehi` DATE NULL,
  `FechaAprov_SolVeh` DATETIME NULL,
  `FechaSali_SolVeh` DATETIME NULL,
  `FehaRet_SolVeh` DATE NULL,
  `FolioProd_SolVeh` VARCHAR(45) NULL,
  PRIMARY KEY (`idSolicitud_Vehiculo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `INE_Inventarios`.`Solicitud_Viaticos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `INE_Inventarios`.`Solicitud_Viaticos` (
  `idViaticos` INT NOT NULL AUTO_INCREMENT,
  `Fol_Viat` VARCHAR(45) NULL,
  `FehaSol_Viat` VARCHAR(45) NULL,
  `FechaAprov_Viat` DATE NULL,
  `FechaSal_Viat` DATE NULL,
  `Personal_Viat` VARCHAR(45) NULL,
  `Dias_Viat` VARCHAR(45) NULL,
  `Lugar_Viat` VARCHAR(45) NULL,
  `Act_Viat` VARCHAR(45) NULL,
  `Status_Viat` VARCHAR(45) NULL,
  `Solicitud_Vehiculo_idSolicitud_Vehiculo` INT NOT NULL,
  `Permotado_Viat` VARCHAR(5) NULL,
  `FechaRet_Viat` DATE NULL,
  PRIMARY KEY (`idViaticos`, `Solicitud_Vehiculo_idSolicitud_Vehiculo`),
  INDEX `fk_Viaticos_Solicitud_Vehiculo1_idx` (`Solicitud_Vehiculo_idSolicitud_Vehiculo` ASC),
  CONSTRAINT `fk_Viaticos_Solicitud_Vehiculo1`
    FOREIGN KEY (`Solicitud_Vehiculo_idSolicitud_Vehiculo`)
    REFERENCES `INE_Inventarios`.`Solicitud_Vehiculo` (`idSolicitud_Vehiculo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `INE_Inventarios`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `INE_Inventarios`.`Usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `Password_Usr` VARCHAR(45) NULL,
  `Empleado_RFC_Emp` VARCHAR(20) NOT NULL,
  `Tipo_Usr_idTipo_Usr` INT NOT NULL,
  `Viaticos_idViaticos` INT NOT NULL,
  `Viaticos_Solicitud_Vehiculo_idSolicitud_Vehiculo` INT NOT NULL,
  PRIMARY KEY (`idUsuario`, `Empleado_RFC_Emp`, `Tipo_Usr_idTipo_Usr`, `Viaticos_idViaticos`, `Viaticos_Solicitud_Vehiculo_idSolicitud_Vehiculo`),
  INDEX `fk_Usuario_Empleado1_idx` (`Empleado_RFC_Emp` ASC),
  INDEX `fk_Usuario_Tipo_Usr1_idx` (`Tipo_Usr_idTipo_Usr` ASC),
  INDEX `fk_Usuario_Viaticos1_idx` (`Viaticos_idViaticos` ASC, `Viaticos_Solicitud_Vehiculo_idSolicitud_Vehiculo` ASC),
  CONSTRAINT `fk_Usuario_Empleado1`
    FOREIGN KEY (`Empleado_RFC_Emp`)
    REFERENCES `INE_Inventarios`.`Empleado` (`RFC_Emp`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuario_Tipo_Usr1`
    FOREIGN KEY (`Tipo_Usr_idTipo_Usr`)
    REFERENCES `INE_Inventarios`.`Tipo_Usr` (`idTipo_Usr`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuario_Viaticos1`
    FOREIGN KEY (`Viaticos_idViaticos` , `Viaticos_Solicitud_Vehiculo_idSolicitud_Vehiculo`)
    REFERENCES `INE_Inventarios`.`Solicitud_Viaticos` (`idViaticos` , `Solicitud_Vehiculo_idSolicitud_Vehiculo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `INE_Inventarios`.`Control`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `INE_Inventarios`.`Control` (
  `idControl` INT NOT NULL AUTO_INCREMENT,
  `Permisos_idPermisos` INT NOT NULL,
  `Asignacion_Usr_idAsignacion` INT NOT NULL,
  `Solicitudes_idSolicitudes` INT NOT NULL,
  `Respuesta_idRespuesta` INT NOT NULL,
  `Usuario_idUsuario` INT NOT NULL,
  PRIMARY KEY (`idControl`, `Permisos_idPermisos`, `Asignacion_Usr_idAsignacion`, `Solicitudes_idSolicitudes`, `Respuesta_idRespuesta`, `Usuario_idUsuario`),
  INDEX `fk_Usuario_Permisos1_idx` (`Permisos_idPermisos` ASC),
  INDEX `fk_Usuario_Asignacion_Usr1_idx` (`Asignacion_Usr_idAsignacion` ASC),
  INDEX `fk_Control_Solicitudes1_idx` (`Solicitudes_idSolicitudes` ASC),
  INDEX `fk_Control_Respuesta1_idx` (`Respuesta_idRespuesta` ASC),
  INDEX `fk_Control_Usuario1_idx` (`Usuario_idUsuario` ASC),
  CONSTRAINT `fk_Usuario_Permisos1`
    FOREIGN KEY (`Permisos_idPermisos`)
    REFERENCES `INE_Inventarios`.`Permisos` (`idPermisos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuario_Asignacion_Usr1`
    FOREIGN KEY (`Asignacion_Usr_idAsignacion`)
    REFERENCES `INE_Inventarios`.`Asignacion_Usr` (`idAsignacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Control_Solicitudes1`
    FOREIGN KEY (`Solicitudes_idSolicitudes`)
    REFERENCES `INE_Inventarios`.`Solicitudes` (`idSolicitudes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Control_Respuesta1`
    FOREIGN KEY (`Respuesta_idRespuesta`)
    REFERENCES `INE_Inventarios`.`Respuesta` (`idRespuesta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Control_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `INE_Inventarios`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `INE_Inventarios`.`Clasificacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `INE_Inventarios`.`Clasificacion` (
  `idClasificacion` INT NOT NULL AUTO_INCREMENT,
  `Folio_Clas` VARCHAR(45) NULL,
  `Nom_Clas` VARCHAR(45) NULL,
  `Stock_Clas` VARCHAR(45) NULL,
  PRIMARY KEY (`idClasificacion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `INE_Inventarios`.`Estado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `INE_Inventarios`.`Estado` (
  `idEstado` INT NOT NULL AUTO_INCREMENT,
  `Nombre_Est` VARCHAR(45) NULL,
  PRIMARY KEY (`idEstado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `INE_Inventarios`.`Fotos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `INE_Inventarios`.`Fotos` (
  `idFotos` INT NOT NULL AUTO_INCREMENT,
  `FotoA_Fot` LONGBLOB NULL,
  `FotoB_Fot` LONGBLOB NULL,
  `FotoC_Fot` LONGBLOB NULL,
  `FotoD_Fot` LONGBLOB NULL,
  `FolioClas_Fot` VARCHAR(45) NULL,
  PRIMARY KEY (`idFotos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `INE_Inventarios`.`Almacen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `INE_Inventarios`.`Almacen` (
  `idAlmacen` INT NOT NULL AUTO_INCREMENT,
  `Nombre_Alm` VARCHAR(45) NULL,
  `Capacidad_Alm` VARCHAR(45) NULL,
  `Disponibilidad_Alm` CHAR(1) NULL,
  PRIMARY KEY (`idAlmacen`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `INE_Inventarios`.`Car_Esp`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `INE_Inventarios`.`Car_Esp` (
  `idCar_Esp` INT NOT NULL AUTO_INCREMENT,
  `Nombre_CarEsp` VARCHAR(45) NULL,
  PRIMARY KEY (`idCar_Esp`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `INE_Inventarios`.`Tipo_Stock`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `INE_Inventarios`.`Tipo_Stock` (
  `idTipoStock` INT NOT NULL AUTO_INCREMENT,
  `Nombre_TipStock` VARCHAR(45) NULL,
  PRIMARY KEY (`idTipoStock`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `INE_Inventarios`.`Productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `INE_Inventarios`.`Productos` (
  `idProductos` INT NOT NULL AUTO_INCREMENT,
  `Clasificacion_idClasificacion` INT NOT NULL,
  `Estado_idEstado` INT NOT NULL,
  `Fotos_idFotos` INT NOT NULL,
  `Car_Esp_idCar_Esp` INT NOT NULL,
  `TipoStock_idTipoStock` INT NOT NULL,
  `Almacen_idAlmacen` INT NOT NULL,
  `Asignacion_Usr_idAsignacion` INT NOT NULL,
  `Nom_Prod` VARCHAR(45) NULL,
  `FolioClas_Prod` VARCHAR(45) NULL,
  `Des_Prod` VARCHAR(255) NULL,
  `FechaComp_Prod` DATE NULL,
  `Stoc_Prod` INT NULL,
  `StockMin_Prod` INT NULL,
  `Obs_Prod` VARCHAR(255) NULL,
  `NoFact_Prod` VARCHAR(45) NULL,
  PRIMARY KEY (`idProductos`, `Clasificacion_idClasificacion`, `Estado_idEstado`, `Fotos_idFotos`, `Car_Esp_idCar_Esp`, `TipoStock_idTipoStock`, `Almacen_idAlmacen`),
  INDEX `fk_Productos_Clasificacion1_idx` (`Clasificacion_idClasificacion` ASC),
  INDEX `fk_Productos_Estado1_idx` (`Estado_idEstado` ASC),
  INDEX `fk_Productos_Fotos1_idx` (`Fotos_idFotos` ASC),
  INDEX `fk_Productos_Asignacion_Usr1_idx` (`Asignacion_Usr_idAsignacion` ASC),
  INDEX `fk_Productos_Almacen1_idx` (`Almacen_idAlmacen` ASC),
  INDEX `fk_Productos_Car_Esp1_idx` (`Car_Esp_idCar_Esp` ASC),
  INDEX `fk_Productos_TipoStock1_idx` (`TipoStock_idTipoStock` ASC),
  CONSTRAINT `fk_Productos_Clasificacion1`
    FOREIGN KEY (`Clasificacion_idClasificacion`)
    REFERENCES `INE_Inventarios`.`Clasificacion` (`idClasificacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Productos_Estado1`
    FOREIGN KEY (`Estado_idEstado`)
    REFERENCES `INE_Inventarios`.`Estado` (`idEstado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Productos_Fotos1`
    FOREIGN KEY (`Fotos_idFotos`)
    REFERENCES `INE_Inventarios`.`Fotos` (`idFotos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Productos_Asignacion_Usr1`
    FOREIGN KEY (`Asignacion_Usr_idAsignacion`)
    REFERENCES `INE_Inventarios`.`Asignacion_Usr` (`idAsignacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Productos_Almacen1`
    FOREIGN KEY (`Almacen_idAlmacen`)
    REFERENCES `INE_Inventarios`.`Almacen` (`idAlmacen`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Productos_Car_Esp1`
    FOREIGN KEY (`Car_Esp_idCar_Esp`)
    REFERENCES `INE_Inventarios`.`Car_Esp` (`idCar_Esp`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Productos_TipoStock1`
    FOREIGN KEY (`TipoStock_idTipoStock`)
    REFERENCES `INE_Inventarios`.`Tipo_Stock` (`idTipoStock`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `INE_Inventarios`.`Datos_Esp`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `INE_Inventarios`.`Datos_Esp` (
  `idDatos_Esp` INT NOT NULL AUTO_INCREMENT,
  `Nombre_Dat` VARCHAR(45) NULL,
  `Car_Esp_idCar_Esp` INT NOT NULL,
  PRIMARY KEY (`idDatos_Esp`, `Car_Esp_idCar_Esp`),
  INDEX `fk_Datos_Esp_Car_Esp1_idx` (`Car_Esp_idCar_Esp` ASC),
  CONSTRAINT `fk_Datos_Esp_Car_Esp1`
    FOREIGN KEY (`Car_Esp_idCar_Esp`)
    REFERENCES `INE_Inventarios`.`Car_Esp` (`idCar_Esp`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `INE_Inventarios`.`Informes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `INE_Inventarios`.`Informes` (
  `idInformes` INT NOT NULL AUTO_INCREMENT,
  `Viaticos_idViaticos` INT NOT NULL,
  `Actividad_Infor` VARCHAR(45) NULL,
  `Status_Infor` VARCHAR(45) NULL,
  `Fecha_Infor` DATE NULL,
  PRIMARY KEY (`idInformes`, `Viaticos_idViaticos`),
  INDEX `fk_Informes_Viaticos1_idx` (`Viaticos_idViaticos` ASC),
  CONSTRAINT `fk_Informes_Viaticos1`
    FOREIGN KEY (`Viaticos_idViaticos`)
    REFERENCES `INE_Inventarios`.`Solicitud_Viaticos` (`idViaticos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `INE_Inventarios`.`Movimientos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `INE_Inventarios`.`Movimientos` (
  `idMovimientos` INT NOT NULL AUTO_INCREMENT,
  `Fecha_Mov` DATE NULL,
  `Status_Mov` VARCHAR(45) NULL,
  `Obsr_Mov` VARCHAR(45) NULL,
  PRIMARY KEY (`idMovimientos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `INE_Inventarios`.`Modulo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `INE_Inventarios`.`Modulo` (
  `idModulo` INT NOT NULL AUTO_INCREMENT,
  `Nombre_Mod` VARCHAR(45) NULL,
  PRIMARY KEY (`idModulo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `INE_Inventarios`.`Privilegios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `INE_Inventarios`.`Privilegios` (
  `idPrivilegios` INT NOT NULL,
  `Agregar_Priv` CHAR(1) NULL,
  `Borrar_Priv` CHAR(1) NULL,
  `Actualizar_Priv` CHAR(1) NULL,
  `Visualizar_Priv` CHAR(1) NULL,
  `Tipo_Usr_idTipo_Usr` INT NOT NULL,
  `Modulo_idModulo` INT NOT NULL,
  PRIMARY KEY (`idPrivilegios`, `Tipo_Usr_idTipo_Usr`, `Modulo_idModulo`),
  INDEX `fk_Privilegios_Tipo_Usr1_idx` (`Tipo_Usr_idTipo_Usr` ASC),
  INDEX `fk_Privilegios_Modulo1_idx` (`Modulo_idModulo` ASC),
  CONSTRAINT `fk_Privilegios_Tipo_Usr1`
    FOREIGN KEY (`Tipo_Usr_idTipo_Usr`)
    REFERENCES `INE_Inventarios`.`Tipo_Usr` (`idTipo_Usr`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Privilegios_Modulo1`
    FOREIGN KEY (`Modulo_idModulo`)
    REFERENCES `INE_Inventarios`.`Modulo` (`idModulo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `INE_Inventarios`.`Contenido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `INE_Inventarios`.`Contenido` (
  `idContenido` INT NOT NULL AUTO_INCREMENT,
  `Contenido_Cont` VARCHAR(250) NULL,
  `FolioClas_Cont` VARCHAR(45) NULL,
  `Datos_Esp_idDatos_Esp` INT NOT NULL,
  PRIMARY KEY (`idContenido`, `Datos_Esp_idDatos_Esp`),
  INDEX `fk_Contenido_Datos_Esp1_idx` (`Datos_Esp_idDatos_Esp` ASC),
  CONSTRAINT `fk_Contenido_Datos_Esp1`
    FOREIGN KEY (`Datos_Esp_idDatos_Esp`)
    REFERENCES `INE_Inventarios`.`Datos_Esp` (`idDatos_Esp`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
